import { AppType } from "next/app";
import { Session } from "next-auth";
import { SessionProvider } from "next-auth/react";
import { trpc } from "../utils/trpc";
import "../styles/globals.css";
import { Navbar } from "../components/Navbar";
import Head from "next/head";
import { useState, useEffect } from "react";
import router from "next/router";

const MyApp: AppType<{ session: Session | null }> = ({
  Component,
  pageProps: { session, ...pageProps },
}) => {
  const [token, setToken] = useState("");

  useEffect(() => {
    const storedToken = localStorage.getItem("token");
    if (storedToken) {
      setToken(storedToken);
    }
  }, []);

  const handleSignOut = () => {
    localStorage.removeItem("token");
    setToken("");
    router.push("/");
  };

  const handleSignIn = async (token: string) => {
    setToken(token);
    router.push("/myteams");
  };

  return (
    <SessionProvider session={session}>
      <Head>
        <title>Paste & Save</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar token={token} handleSignOut={handleSignOut} />
      <Component {...pageProps} setToken={setToken} handleSignIn={handleSignIn} />
    </SessionProvider>
  );
};

export default trpc.withTRPC(MyApp);
