import { type NextPage } from "next";
import Head from "next/head";
import Home from "../components/signupFormComponent";

const HomePage: NextPage = () => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex items-center justify-center h-[90%]">
        <div id="feedback-form">
          <h2 className="header">Sign up</h2>
          <div>
            <Home/>
          </div>
        </div>
      </main>
    </>
  );
};

export default HomePage;
