import { type NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import jwt from "jsonwebtoken";

const KEY = 'azertyuiopqsdfghjklmwxcvbn';

const Myteams: NextPage = () => {

  const [username, setUsername] = useState('');

  useEffect(() => {
    const token = localStorage.getItem('token');
    if (token) {
    const decodedToken = jwt.verify(token, KEY);
    if (typeof decodedToken !== 'string') {
    const username = decodedToken.username;
    setUsername(username);
    }
    }
    }, []);
    
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-center h-[90%]">
      <div>Hello {username}</div>
      </main>
    </>
  );
};

export default Myteams;
